"""Typed node builders for every kind except `block`, styled spans, the
props every node takes, and handlers attached to nodes.

Children are positional, props keyword-only; snake_case keywords map to the
wire's camelCase names (`max_lines` is `maxLines`), and `class_` is `el`'s
`class`. `props={...}` sets any prop untyped, and `node(kind, props,
children)` builds any kind."""

from ._html import AttrValue, ElementBuilder, Html, InputBuilder, el, html
from ._kinds import (
    agent,
    ansi,
    badge,
    card,
    chart,
    checklist,
    code,
    col,
    diff,
    editor,
    effort,
    elapsed,
    icon,
    image,
    item,
    kbd,
    kv,
    math,
    md,
    meter,
    node,
    overlay,
    picker,
    prefs,
    progress,
    rate,
    row,
    rows,
    rule,
    section,
    seg,
    shimmer,
    spacer,
    span,
    spinner,
    status,
    table,
    tabs,
    text,
    toast,
    tool,
    tree,
)
from ._node import BaseProps, Common, CommonNoMax, CommonNoTitle, Handler, Handlers, Node, PickerCommon
from ._shadow import input, list  # noqa: A004
from ._types import (
    ActionControl,
    Actions,
    AgentRetry,
    AgentStats,
    AgentStatus,
    AgentTool,
    Align,
    Badge,
    Bounds,
    CaretAnchor,
    ChartCol,
    ChartKind,
    ChartPoint,
    ChecklistItem,
    ChecklistMode,
    ChoiceControl,
    ChoiceOption,
    CodeMark,
    ColumnFormat,
    Decor,
    DiffMode,
    EffortLevel,
    ElapsedFormat,
    Extent,
    Fx,
    Gap,
    Hunk,
    IconName,
    InputType,
    ItemStatus,
    Justify,
    KeysControl,
    KvItem,
    KvLayout,
    LinesPreview,
    ListMax,
    Mark,
    MeterCell,
    MeterCellProps,
    MeterMark,
    MeterPart,
    MeterStyle,
    MultiControl,
    NodeAnchor,
    NumberControl,
    OverlayPlace,
    OverlaySize,
    Phase,
    PickerAction,
    PickerChip,
    PickerColumn,
    PickerConfirm,
    PickerFocus,
    PickerGroup,
    PickerItem,
    PickerLayout,
    PickerMark,
    PickerPreview,
    PickerScope,
    PickerSize,
    PickerState,
    PickerStrip,
    PickerStripItem,
    PickerTab,
    PrefsControl,
    PrefsEditing,
    PrefsPage,
    PrefsRow,
    PrefsSection,
    ShimmerMode,
    ShimmerPalette,
    Size3,
    Span,
    Spans,
    SpinnerStyle,
    Status,
    SwitchControl,
    Tab,
    TableCol,
    TableRow,
    Tag,
    TailPreview,
    TargetKind,
    Text,
    TextAlign,
    TextControl,
    Thresholds,
    Tone,
    ToolButton,
    ToolFrame,
    TreeNode,
    Truncate,
    Wrap,
)

__all__ = [
    "ActionControl", "Actions", "AgentRetry", "AgentStats", "AgentStatus", "AgentTool", "Align",
    "AttrValue", "Badge", "BaseProps", "Bounds", "CaretAnchor", "ChartCol", "ChartKind",
    "ChartPoint", "ChecklistItem", "ChecklistMode", "ChoiceControl", "ChoiceOption", "CodeMark",
    "ColumnFormat", "Common", "CommonNoMax", "CommonNoTitle", "Decor", "DiffMode", "EffortLevel",
    "ElapsedFormat", "ElementBuilder", "Extent", "Fx", "Gap", "Handler", "Handlers", "Html",
    "Hunk", "IconName", "InputBuilder", "InputType", "ItemStatus", "Justify", "KeysControl",
    "KvItem", "KvLayout", "LinesPreview", "ListMax", "Mark", "MeterCell", "MeterCellProps", "MeterMark",
    "MeterPart", "MeterStyle", "MultiControl", "Node", "NodeAnchor", "NumberControl",
    "OverlayPlace", "OverlaySize", "Phase", "PickerAction", "PickerChip", "PickerColumn",
    "PickerCommon", "PickerConfirm", "PickerFocus", "PickerGroup", "PickerItem", "PickerLayout",
    "PickerMark", "PickerPreview", "PickerScope", "PickerSize", "PickerState", "PickerStrip",
    "PickerStripItem", "PickerTab", "PrefsControl", "PrefsEditing", "PrefsPage", "PrefsRow",
    "PrefsSection", "ShimmerMode", "ShimmerPalette", "Size3", "Span", "Spans", "SpinnerStyle",
    "Status", "SwitchControl", "Tab", "TableCol", "TableRow", "Tag", "TailPreview", "TargetKind",
    "Text", "TextAlign", "TextControl", "Thresholds", "Tone", "ToolButton",
    "ToolFrame", "TreeNode", "Truncate", "Wrap",
    "agent", "ansi", "badge", "card", "chart", "checklist", "code", "col", "diff", "editor",
    "effort", "el", "elapsed", "html", "icon", "image", "input", "item", "kbd", "kv", "list",
    "math", "md", "meter", "node", "overlay", "picker", "prefs", "progress", "rate", "row",
    "rows", "rule", "section", "seg", "shimmer", "spacer", "span", "spinner", "status", "table",
    "tabs", "text", "toast", "tool", "tree",
]  # fmt: skip
